### ISSUE TITLE
please add sleep time until full energy. 

### ISSUE THREAD

**Issue by Moe5M** [NabiKAZ/TapSwap-Scripts#1]
Love the script! Can you add a sleep time for full energy?

**Comment by NabiKAZ** [comment]
Thank you for your attention.
You can increase the delay (the variable in the first line of the code) so that appropriate clicks are always made when the energy is filled.
For example, if 5 energy is filled every second and you use 10 energy with each tap. You can set the delay to 2 seconds. which you enter 2000 milliseconds.
